export const SSR_PATHS = new Set([
  // TCM Platform Core Routes
  "/",
  "/zh",
  "/library",
  "/zh/library",
  "/learn",
  "/zh/learn",
  "/glossary",
  "/zh/glossary",
  "/history",
  "/zh/history",
  "/about",
  "/zh/about",
  "/contact",
  "/zh/contact",
  "/terms",
  "/zh/terms",
  "/privacy",
  "/zh/privacy",
  "/blog",
  "/zh/blog",
  "/search",
  "/zh/search",
  
  // Ancient Book Routes
  "/book/bencao-gangmu",
  "/zh/book/bencao-gangmu",
  "/book/huangdi-neijing",
  "/zh/book/huangdi-neijing",
  "/book/jiayi-jing",
  "/zh/book/jiayi-jing",
  "/book/jinkui-yaolue",
  "/zh/book/jinkui-yaolue",
  "/book/mai-jing",
  "/zh/book/mai-jing",
  "/book/qianjin-fang",
  "/zh/book/qianjin-fang",
  "/book/shanghan-lun",
  "/zh/book/shanghan-lun",
  "/book/shanghan-zabing-lun",
  "/zh/book/shanghan-zabing-lun",
  "/book/wenzhen-xue",
  "/zh/book/wenzhen-xue",
  "/book/yixue-rumen",
  "/zh/book/yixue-rumen"
]);