import fs from 'fs';
import path from 'path';
const listManufacturerSlugs = () => {
  const dir = path.join(process.cwd(), 'content', 'manufacturers', 'en');
  try {
    const files = fs.readdirSync(dir);
    return files.filter(f => f.endsWith('.md')).map(f => f.replace(/\.md$/, ''));
  } catch {
    return [];
  }
};
import { ct } from '../src/locales/en/data/ct/index';
// MRI data might not be exported yet or I need to find where it is.
// Let's assume for now I only have CT available in the index I saw.

const OUTPUT_FILE = path.join(process.cwd(), 'supabase/migrations/011_sync_all_data.sql');

const generateSql = () => {
  let sql = `-- 011_sync_all_data.sql
-- Auto-generated by scripts/generate-data-migration.ts
-- Syncs manufacturers and devices from src/locales/en/data to database

`;

  // 1. Manufacturers
  sql += `-- Sync Manufacturers\n`;
  listManufacturerSlugs().forEach(slug => {
    const name = slug.replace(/-/g, ' ').replace(/\b\w/g, s => s.toUpperCase());
    const description = '';
    const country = 'Unknown';
    sql += `
INSERT INTO public.manufacturers (slug, name, country, description)
VALUES ('${slug}', '${name.replace(/'/g, "''")}', '${country}', '${description}')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description;
`;
  });

  // 2. Devices
  sql += `\n-- Sync Devices\n`;
  
  // CT
  Object.values(ct).forEach(d => {
    const name = d.name.replace(/'/g, "''");
    const description = (d.description || '').replace(/'/g, "''");
    const slug = d.id;
    const manufacturerSlug = d.manufacturerId;
    const type = 'ct'; 
    const category = d.category || 'general'; // mid-range etc.
    
    // Determine device type slug
    let deviceTypeSlug = 'ct-scanner';
    const slices = d.specifications?.slices;
    if (slices === 16) deviceTypeSlug = '16-slice-ct';
    else if (slices === 32) deviceTypeSlug = '32-slice-ct';
    else if (slices === 64) deviceTypeSlug = '64-slice-ct';
    else if (slices === 128) deviceTypeSlug = '128-slice-ct';
    else if (slices === 256) deviceTypeSlug = '256-slice-ct';
    else if (slices === 320) deviceTypeSlug = '320-slice-ct';

    // Need to get manufacturer_id from slug
    // We can use a subquery
    
    sql += `
INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  '${slug}', 
  '${name}', 
  '${description}', 
  '${category}', 
  (SELECT id FROM public.manufacturers WHERE slug = '${manufacturerSlug}'),
  (SELECT id FROM public.device_types WHERE slug = '${deviceTypeSlug}')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;
`;
  });
  
  return sql;
};

const sql = generateSql();
fs.writeFileSync(OUTPUT_FILE, sql);
console.log(`Generated ${OUTPUT_FILE}`);
