/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IndexBackupRouteImport } from './routes/index-backup'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis/index'
import { Route as ResourcesTechnologyRouteImport } from './routes/resources/technology'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as KnowledgeTechnologyRouteImport } from './routes/knowledge/technology'
import { Route as KnowledgeHistoryRouteImport } from './routes/knowledge/history'
import { Route as HistorySlugRouteImport } from './routes/history.$slug'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AnalysisMarketRouteImport } from './routes/analysis/market'
import { Route as AnalysisExpertRouteImport } from './routes/analysis/expert'
import { Route as KnowledgeHistorySlugRouteImport } from './routes/knowledge/history.$slug'
import { Route as BookBookIdChapterChapterIdRouteImport } from './routes/book.$bookId.chapter.$chapterId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexBackupRoute = IndexBackupRouteImport.update({
  id: '/index-backup',
  path: '/index-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTechnologyRoute = ResourcesTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => ResourcesRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const KnowledgeTechnologyRoute = KnowledgeTechnologyRouteImport.update({
  id: '/knowledge/technology',
  path: '/knowledge/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHistoryRoute = KnowledgeHistoryRouteImport.update({
  id: '/knowledge/history',
  path: '/knowledge/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySlugRoute = HistorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HistoryRoute,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AnalysisMarketRoute = AnalysisMarketRouteImport.update({
  id: '/analysis/market',
  path: '/analysis/market',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisExpertRoute = AnalysisExpertRouteImport.update({
  id: '/analysis/expert',
  path: '/analysis/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHistorySlugRoute = KnowledgeHistorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeHistoryRoute,
} as any)
const BookBookIdChapterChapterIdRoute =
  BookBookIdChapterChapterIdRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => BookBookIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/glossary': typeof GlossaryRoute
  '/history': typeof HistoryRouteWithChildren
  '/index-backup': typeof IndexBackupRoute
  '/learn': typeof LearnRouteWithChildren
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/analysis/expert': typeof AnalysisExpertRoute
  '/analysis/market': typeof AnalysisMarketRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$bookId': typeof BookBookIdRouteWithChildren
  '/history/$slug': typeof HistorySlugRoute
  '/knowledge/history': typeof KnowledgeHistoryRouteWithChildren
  '/knowledge/technology': typeof KnowledgeTechnologyRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/resources/technology': typeof ResourcesTechnologyRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/knowledge/history/$slug': typeof KnowledgeHistorySlugRoute
  '/book/$bookId/chapter/$chapterId': typeof BookBookIdChapterChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/glossary': typeof GlossaryRoute
  '/history': typeof HistoryRouteWithChildren
  '/index-backup': typeof IndexBackupRoute
  '/learn': typeof LearnRouteWithChildren
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/analysis/expert': typeof AnalysisExpertRoute
  '/analysis/market': typeof AnalysisMarketRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$bookId': typeof BookBookIdRouteWithChildren
  '/history/$slug': typeof HistorySlugRoute
  '/knowledge/history': typeof KnowledgeHistoryRouteWithChildren
  '/knowledge/technology': typeof KnowledgeTechnologyRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/resources/technology': typeof ResourcesTechnologyRoute
  '/analysis': typeof AnalysisIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/knowledge/history/$slug': typeof KnowledgeHistorySlugRoute
  '/book/$bookId/chapter/$chapterId': typeof BookBookIdChapterChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/glossary': typeof GlossaryRoute
  '/history': typeof HistoryRouteWithChildren
  '/index-backup': typeof IndexBackupRoute
  '/learn': typeof LearnRouteWithChildren
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/analysis/expert': typeof AnalysisExpertRoute
  '/analysis/market': typeof AnalysisMarketRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$bookId': typeof BookBookIdRouteWithChildren
  '/history/$slug': typeof HistorySlugRoute
  '/knowledge/history': typeof KnowledgeHistoryRouteWithChildren
  '/knowledge/technology': typeof KnowledgeTechnologyRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/resources/technology': typeof ResourcesTechnologyRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/knowledge/history/$slug': typeof KnowledgeHistorySlugRoute
  '/book/$bookId/chapter/$chapterId': typeof BookBookIdChapterChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/glossary'
    | '/history'
    | '/index-backup'
    | '/learn'
    | '/library'
    | '/privacy'
    | '/research'
    | '/resources'
    | '/search'
    | '/terms'
    | '/analysis/expert'
    | '/analysis/market'
    | '/blog/$slug'
    | '/book/$bookId'
    | '/history/$slug'
    | '/knowledge/history'
    | '/knowledge/technology'
    | '/learn/$slug'
    | '/resources/technology'
    | '/analysis/'
    | '/knowledge/'
    | '/knowledge/history/$slug'
    | '/book/$bookId/chapter/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/glossary'
    | '/history'
    | '/index-backup'
    | '/learn'
    | '/library'
    | '/privacy'
    | '/research'
    | '/resources'
    | '/search'
    | '/terms'
    | '/analysis/expert'
    | '/analysis/market'
    | '/blog/$slug'
    | '/book/$bookId'
    | '/history/$slug'
    | '/knowledge/history'
    | '/knowledge/technology'
    | '/learn/$slug'
    | '/resources/technology'
    | '/analysis'
    | '/knowledge'
    | '/knowledge/history/$slug'
    | '/book/$bookId/chapter/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/glossary'
    | '/history'
    | '/index-backup'
    | '/learn'
    | '/library'
    | '/privacy'
    | '/research'
    | '/resources'
    | '/search'
    | '/terms'
    | '/analysis/expert'
    | '/analysis/market'
    | '/blog/$slug'
    | '/book/$bookId'
    | '/history/$slug'
    | '/knowledge/history'
    | '/knowledge/technology'
    | '/learn/$slug'
    | '/resources/technology'
    | '/analysis/'
    | '/knowledge/'
    | '/knowledge/history/$slug'
    | '/book/$bookId/chapter/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  GlossaryRoute: typeof GlossaryRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  IndexBackupRoute: typeof IndexBackupRoute
  LearnRoute: typeof LearnRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  PrivacyRoute: typeof PrivacyRoute
  ResearchRoute: typeof ResearchRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  AnalysisExpertRoute: typeof AnalysisExpertRoute
  AnalysisMarketRoute: typeof AnalysisMarketRoute
  BookBookIdRoute: typeof BookBookIdRouteWithChildren
  KnowledgeHistoryRoute: typeof KnowledgeHistoryRouteWithChildren
  KnowledgeTechnologyRoute: typeof KnowledgeTechnologyRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index-backup': {
      id: '/index-backup'
      path: '/index-backup'
      fullPath: '/index-backup'
      preLoaderRoute: typeof IndexBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/technology': {
      id: '/resources/technology'
      path: '/technology'
      fullPath: '/resources/technology'
      preLoaderRoute: typeof ResourcesTechnologyRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/knowledge/technology': {
      id: '/knowledge/technology'
      path: '/knowledge/technology'
      fullPath: '/knowledge/technology'
      preLoaderRoute: typeof KnowledgeTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/history': {
      id: '/knowledge/history'
      path: '/knowledge/history'
      fullPath: '/knowledge/history'
      preLoaderRoute: typeof KnowledgeHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$slug': {
      id: '/history/$slug'
      path: '/$slug'
      fullPath: '/history/$slug'
      preLoaderRoute: typeof HistorySlugRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/analysis/market': {
      id: '/analysis/market'
      path: '/analysis/market'
      fullPath: '/analysis/market'
      preLoaderRoute: typeof AnalysisMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/expert': {
      id: '/analysis/expert'
      path: '/analysis/expert'
      fullPath: '/analysis/expert'
      preLoaderRoute: typeof AnalysisExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/history/$slug': {
      id: '/knowledge/history/$slug'
      path: '/$slug'
      fullPath: '/knowledge/history/$slug'
      preLoaderRoute: typeof KnowledgeHistorySlugRouteImport
      parentRoute: typeof KnowledgeHistoryRoute
    }
    '/book/$bookId/chapter/$chapterId': {
      id: '/book/$bookId/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/book/$bookId/chapter/$chapterId'
      preLoaderRoute: typeof BookBookIdChapterChapterIdRouteImport
      parentRoute: typeof BookBookIdRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface HistoryRouteChildren {
  HistorySlugRoute: typeof HistorySlugRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistorySlugRoute: HistorySlugRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface ResourcesRouteChildren {
  ResourcesTechnologyRoute: typeof ResourcesTechnologyRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesTechnologyRoute: ResourcesTechnologyRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface BookBookIdRouteChildren {
  BookBookIdChapterChapterIdRoute: typeof BookBookIdChapterChapterIdRoute
}

const BookBookIdRouteChildren: BookBookIdRouteChildren = {
  BookBookIdChapterChapterIdRoute: BookBookIdChapterChapterIdRoute,
}

const BookBookIdRouteWithChildren = BookBookIdRoute._addFileChildren(
  BookBookIdRouteChildren,
)

interface KnowledgeHistoryRouteChildren {
  KnowledgeHistorySlugRoute: typeof KnowledgeHistorySlugRoute
}

const KnowledgeHistoryRouteChildren: KnowledgeHistoryRouteChildren = {
  KnowledgeHistorySlugRoute: KnowledgeHistorySlugRoute,
}

const KnowledgeHistoryRouteWithChildren =
  KnowledgeHistoryRoute._addFileChildren(KnowledgeHistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  GlossaryRoute: GlossaryRoute,
  HistoryRoute: HistoryRouteWithChildren,
  IndexBackupRoute: IndexBackupRoute,
  LearnRoute: LearnRouteWithChildren,
  LibraryRoute: LibraryRoute,
  PrivacyRoute: PrivacyRoute,
  ResearchRoute: ResearchRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  AnalysisExpertRoute: AnalysisExpertRoute,
  AnalysisMarketRoute: AnalysisMarketRoute,
  BookBookIdRoute: BookBookIdRouteWithChildren,
  KnowledgeHistoryRoute: KnowledgeHistoryRouteWithChildren,
  KnowledgeTechnologyRoute: KnowledgeTechnologyRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
