-- 011_sync_all_data.sql
-- Auto-generated by scripts/generate-data-migration.ts
-- Syncs manufacturers and devices from src/locales/en/data to database

-- Sync Manufacturers

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('ge-healthcare', 'GE Healthcare', 'United States', 'Leading global medical technology company, specializing in advanced CT imaging solutions', false)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('siemens-healthineers', 'Siemens Healthineers', 'Germany', 'Pioneer in medical imaging technology, featuring innovative dual-source CT technology', false)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('philips-healthcare', 'Philips Healthcare', 'Netherlands', 'Healthcare technology leader, focused on meaningful innovations in CT imaging', false)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('canon-medical', 'Canon Medical Systems', 'Japan', 'Japanese medical technology company, known for innovative volumetric CT systems', false)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('united-imaging', 'United Imaging', 'China', 'Leading Chinese medical equipment enterprise, dedicated to becoming a world-leading manufacturer', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('neusoft-medical', 'Neusoft Medical', 'China', 'Pioneer in China''s medical equipment industry, focused on accessible healthcare solutions', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('wandong-medical', 'Wandong Medical', 'China', 'Innovative medical imaging technology company.', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('anke-medical', 'Anke Medical', 'China', 'CT equipment and medical imaging technology company.', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('mingfeng-medical', 'Mingfeng Medical', 'China', 'Professional medical imaging solutions provider.', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('sino-vision', 'Sino Vision', 'China', 'High-end CT equipment manufacturer.', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('kaiying-medical', 'Kaiying Medical', 'China', 'Manufacturer of CT and MRI equipment.', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('kangda-medical', 'Kangda Intercontinental', 'China', 'Manufacturer of 32-slice CT equipment.', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('broaden-medical', 'Broaden Medical', 'China', '32-slice CT manufacturer focusing on primary care market.', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

INSERT INTO public.manufacturers (slug, name, country, description, is_chinese)
VALUES ('perlove-medical', 'Perlove Medical', 'China', 'Manufacturer of medical imaging solutions and equipment.', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  description = EXCLUDED.description,
  is_chinese = EXCLUDED.is_chinese;

-- Sync Devices

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'ge-revolution-apex-expert', 
  'Revolution Apex Expert', 
  'High-end CT system, a flagship product with integrated AI technology.', 
  'high-end', 
  (SELECT id FROM public.manufacturers WHERE slug = 'ge-healthcare'),
  (SELECT id FROM public.device_types WHERE slug = 'ct-scanner')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'ge-revolution-ct', 
  'Revolution CT', 
  'Advanced CT system merging innovative technologies for high-performance imaging.', 
  'high-end', 
  (SELECT id FROM public.manufacturers WHERE slug = 'ge-healthcare'),
  (SELECT id FROM public.device_types WHERE slug = 'ct-scanner')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'ge-optima-ct680-expert', 
  'Optima CT680 Expert', 
  'Mid-range CT system, an excellent cost-effective choice for versatile medical imaging.', 
  'mid-range', 
  (SELECT id FROM public.manufacturers WHERE slug = 'ge-healthcare'),
  (SELECT id FROM public.device_types WHERE slug = 'ct-scanner')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'siemens-somatom-drive', 
  'SOMATOM Drive', 
  'High-end CT system with German engineering, providing precision and reliable diagnostic images.', 
  'high-end', 
  (SELECT id FROM public.manufacturers WHERE slug = 'siemens-healthineers'),
  (SELECT id FROM public.device_types WHERE slug = 'ct-scanner')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'siemens-somatom-force', 
  'SOMATOM Force', 
  'Ultra-high-end CT system, the peak of dual-source imaging technology for rapid clinical diagnosis.', 
  'high-end', 
  (SELECT id FROM public.manufacturers WHERE slug = 'siemens-healthineers'),
  (SELECT id FROM public.device_types WHERE slug = 'ct-scanner')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'siemens-somatom-go-up', 
  'Somatom Go Up', 
  'Economical and practical CT system.', 
  'mid-range', 
  (SELECT id FROM public.manufacturers WHERE slug = 'siemens-healthineers'),
  (SELECT id FROM public.device_types WHERE slug = '64-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'philips-spectral-ct', 
  'Spectral CT', 
  'Innovative Spectral CT allowing for precise material identification and advanced tissue characterization.', 
  'high-end', 
  (SELECT id FROM public.manufacturers WHERE slug = 'philips-healthcare'),
  (SELECT id FROM public.device_types WHERE slug = 'ct-scanner')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'philips-incisive-ct', 
  'Incisive CT', 
  'CT system, precise imaging.', 
  'mid-range', 
  (SELECT id FROM public.manufacturers WHERE slug = 'philips-healthcare'),
  (SELECT id FROM public.device_types WHERE slug = '64-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'uih-uct-960-plus', 
  'uCT 960+', 
  'High-end CT system, a world-class product made in China.', 
  'high-end', 
  (SELECT id FROM public.manufacturers WHERE slug = 'united-imaging'),
  (SELECT id FROM public.device_types WHERE slug = 'ct-scanner')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'uih-uct-860', 
  'uCT 860', 
  'Mid-range CT system.', 
  'mid-range', 
  (SELECT id FROM public.manufacturers WHERE slug = 'united-imaging'),
  (SELECT id FROM public.device_types WHERE slug = 'ct-scanner')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'uih-uct-528', 
  'uCT 528', 
  'Mid-range CT system.', 
  'mid-range', 
  (SELECT id FROM public.manufacturers WHERE slug = 'united-imaging'),
  (SELECT id FROM public.device_types WHERE slug = '64-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'neusoft-neuviz-epoch', 
  'NeuViz Epoch', 
  'High-end CT system with flagship performance.', 
  'high-end', 
  (SELECT id FROM public.manufacturers WHERE slug = 'neusoft-medical'),
  (SELECT id FROM public.device_types WHERE slug = 'ct-scanner')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'neusoft-neuviz-128', 
  'NeuViz 128', 
  'Mid-range CT system.', 
  'mid-range', 
  (SELECT id FROM public.manufacturers WHERE slug = 'neusoft-medical'),
  (SELECT id FROM public.device_types WHERE slug = '128-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'neusoft-neuviz-glory', 
  'NeuViz Glory', 
  'High-end CT system.', 
  'high-end', 
  (SELECT id FROM public.manufacturers WHERE slug = 'neusoft-medical'),
  (SELECT id FROM public.device_types WHERE slug = '128-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'canon-aquilion-prime-tsx', 
  'AQUILION PRIME TSX', 
  'CT system.', 
  'mid-range', 
  (SELECT id FROM public.manufacturers WHERE slug = 'canon-medical'),
  (SELECT id FROM public.device_types WHERE slug = '64-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'anke-anatom-64-fit', 
  'ANATOM 64 FIT', 
  'CT system.', 
  'mid-range', 
  (SELECT id FROM public.manufacturers WHERE slug = 'anke-medical'),
  (SELECT id FROM public.device_types WHERE slug = '64-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'anke-anatoma-200', 
  'ANATOMA 200', 
  'CT system.', 
  'entry-level', 
  (SELECT id FROM public.manufacturers WHERE slug = 'anke-medical'),
  (SELECT id FROM public.device_types WHERE slug = '32-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'mingfeng-scintcare-m650', 
  'Scintcare M650', 
  'CT system.', 
  'mid-range', 
  (SELECT id FROM public.manufacturers WHERE slug = 'mingfeng-medical'),
  (SELECT id FROM public.device_types WHERE slug = '64-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'mingfeng-scintcare-blue-755', 
  'Scintcare Blue 755', 
  'CT system.', 
  'high-end', 
  (SELECT id FROM public.manufacturers WHERE slug = 'mingfeng-medical'),
  (SELECT id FROM public.device_types WHERE slug = '128-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;

INSERT INTO public.devices (slug, name, description, category, manufacturer_id, device_type_id)
VALUES (
  'wandong-turbotom-3200s', 
  'TURBOTOM 3200S', 
  'CT system.', 
  'entry-level', 
  (SELECT id FROM public.manufacturers WHERE slug = 'wandong-medical'),
  (SELECT id FROM public.device_types WHERE slug = '32-slice-ct')
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  manufacturer_id = EXCLUDED.manufacturer_id,
  device_type_id = EXCLUDED.device_type_id;
