// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_ENDPOINT = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

declare global {
  // eslint-disable-next-line no-var
  var __SUPABASE_CLIENT__: SupabaseClient<Database> | undefined;
}

function getSupabaseClient(): SupabaseClient<Database> {
  if (!globalThis.__SUPABASE_CLIENT__) {
    globalThis.__SUPABASE_CLIENT__ = createClient<Database>(SUPABASE_ENDPOINT, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? window.localStorage : undefined,
        persistSession: typeof window !== 'undefined',
        autoRefreshToken: typeof window !== 'undefined',
      },
    });
  }
  return globalThis.__SUPABASE_CLIENT__;
}

export const supabase = getSupabaseClient();
